Repository meateam/upload-service, pull requests merged in 2019-05, with the labels that each got.

#20 Develop - Change upload to stream
  go.mod
  go.sum
  main.go
  upload.go
Labels: enhancement

#25 added health check
  .vscode/launch.json
  docker-compose.yml
  main.go
Labels: enhancement

#27 added grpc_health_probe to the container image
  Dockerfile
Labels: enhancement

#26 Develop
  .vscode/launch.json
  Dockerfile
  docker-compose.yml
  main.go
Labels: enhancement

#28 Feature/apm
  .vscode/launch.json
  Dockerfile
  docker-compose.debug.yml
  docker-compose.yml
  go.mod
  go.sum
  main.go
Labels: enhancement, good first issue

#29 Develop - use fork of apmgrpc to ignore grpc health check
  .vscode/launch.json
  Dockerfile
  docker-compose.debug.yml
  docker-compose.yml
  go.mod
  go.sum
  main.go
Labels: enhancement, good first issue

#31 improve Dockerfile caching
  Dockerfile
  Makefile
Labels: enhancement

#33 Feature/logs
  .golangci.yml
  .vscode/launch.json
  Dockerfile
  go.mod
  go.sum
  main.go
Labels: enhancement

#35 update elasticsearch-logger
  go.mod
  go.sum
  main.go
Labels: enhancement

#36 Develop - add elasticsearch logger with APM and tracing
  .golangci.yml
  .vscode/launch.json
  Dockerfile
  go.mod
  go.sum
  main.go
Labels: enhancement

#37 Develop - update elasticsearch-logger
  go.mod
  go.sum
  main.go
Labels: bug, enhancement

#38 Develop - update elasticsearch-logger
  go.mod
  go.sum
  main.go
Labels: bug, enhancement
