Repository meateam/upload-service, pull requests merged in 2019-06, with the labels that each got.

#40 Feature/refactor
  bucket/bucket.go
  bucket/bucket_test.go
  go.mod
  go.sum
  internal/test/helper.go
  main.go
  server/server.go
  upload/handler.go
  upload/service.go
  upload/upload_test.go
Labels: enhancement, refactor

#41 Develop
  bucket/bucket.go
  bucket/bucket_test.go
  go.mod
  go.sum
  internal/test/helper.go
  main.go
  server/server.go
  upload/handler.go
  upload/service.go
  upload/upload_test.go
Labels: enhancement, refactor

#42 update elasticsearch-logger to v1.1.2
  go.mod
  go.sum
Labels: enhancement

#43 update grpc_health_probe version and cleaned go.sum
  Dockerfile
  go.sum
Labels: enhancement, good first issue

#44 Hotfix/region
  bucket/bucket.go
  main.go
  server/server.go
  upload/upload_test.go
Labels: bug, enhancement

#46 Develop
  server/server.go
Labels: bug

#47 Develop
  bucket/bucket.go
  bucket/bucket_test.go
Labels: bug, enhancement
